language: node.js
node_js:
  - "node"

sudo: required

services:
  - docker

install:
  - yarn install

script:
  - yarn build

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t tkrhkaos12/react-test .
  - docker push tkrhkaos12/react-test
