language: node.js
node_js:
  - "node"

sudo: required

services:
  - docker

install:
  - npm install

script:
  - npm run build

after_success:
  - docker login -u
  - docker build -t
  - docker push
